import type { ProductTourStep } from './tour-types.js';

/**
 * Interactive product tour steps.
 * Targets use data-tour attributes added across the UI.
 */
export const PRODUCT_TOUR_STEPS: ProductTourStep[] = [
  {
    id: 'welcome',
    titleKey: 'productTour.steps.welcome.title',
    bodyKey: 'productTour.steps.welcome.body',
    view: 'mailbox',
    placement: 'center',
  },
  {
    id: 'tempEmail',
    titleKey: 'productTour.steps.tempEmail.title',
    bodyKey: 'productTour.steps.tempEmail.body',
    view: 'mailbox',
    target: '[data-tour="account-selector"]',
    placement: 'bottom',
    padding: 6,
  },
  {
    id: 'doubleTapCopy',
    titleKey: 'productTour.steps.doubleTapCopy.title',
    bodyKey: 'productTour.steps.doubleTapCopy.body',
    view: 'mailbox',
    target: '[data-tour="account-selector"]',
    placement: 'bottom',
    padding: 6,
  },
  {
    id: 'createInbox',
    titleKey: 'productTour.steps.createInbox.title',
    bodyKey: 'productTour.steps.createInbox.body',
    view: 'mailbox',
    target: '[data-tour="create-inbox"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'searchFilter',
    titleKey: 'productTour.steps.searchFilter.title',
    bodyKey: 'productTour.steps.searchFilter.body',
    view: 'mailbox',
    target: '[data-tour="search-filter"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'searchPills',
    titleKey: 'productTour.steps.searchPills.title',
    bodyKey: 'productTour.steps.searchPills.body',
    view: 'mailbox',
    target: '[data-tour="search-pills"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'excludeSyntax',
    titleKey: 'productTour.steps.excludeSyntax.title',
    bodyKey: 'productTour.steps.excludeSyntax.body',
    view: 'mailbox',
    target: '[data-tour="search-filter"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'emailList',
    titleKey: 'productTour.steps.emailList.title',
    bodyKey: 'productTour.steps.emailList.body',
    view: 'mailbox',
    target: '[data-tour="email-list-tabs"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'holdSelect',
    titleKey: 'productTour.steps.holdSelect.title',
    bodyKey: 'productTour.steps.holdSelect.body',
    view: 'mailbox',
    target: '[data-tour="email-list-tabs"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'attachmentBadge',
    titleKey: 'productTour.steps.attachmentBadge.title',
    bodyKey: 'productTour.steps.attachmentBadge.body',
    view: 'mailbox',
    target: '[data-tour="attachment-badge"]',
    placement: 'top',
    padding: 4,
  },
  {
    id: 'footerNav',
    titleKey: 'productTour.steps.footerNav.title',
    bodyKey: 'productTour.steps.footerNav.body',
    view: 'mailbox',
    target: '[data-tour="footer-nav"]',
    placement: 'top',
    padding: 6,
  },
  {
    id: 'manageInboxes',
    titleKey: 'productTour.steps.manageInboxes.title',
    bodyKey: 'productTour.steps.manageInboxes.body',
    view: 'addresses',
    target: '[data-tour="manage-tabs"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'autofillHub',
    titleKey: 'productTour.steps.autofillHub.title',
    bodyKey: 'productTour.steps.autofillHub.body',
    view: 'autofill',
    target: '[data-tour="autofill-hub"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'autofillProfiles',
    titleKey: 'productTour.steps.autofillProfiles.title',
    bodyKey: 'productTour.steps.autofillProfiles.body',
    view: 'autofill',
    target: '[data-tour="autofill-tab-profiles"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'autofillCredentials',
    titleKey: 'productTour.steps.autofillCredentials.title',
    bodyKey: 'productTour.steps.autofillCredentials.body',
    view: 'autofill',
    target: '[data-tour="autofill-tab-credentials"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'settings',
    titleKey: 'productTour.steps.settings.title',
    bodyKey: 'productTour.steps.settings.body',
    view: 'settings',
    target: '[data-tour="settings-search"]',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'done',
    titleKey: 'productTour.steps.done.title',
    bodyKey: 'productTour.steps.done.body',
    view: 'mailbox',
    placement: 'center',
  },
];
